embeddings {
  tensor_name: "constant:02500"
  metadata_path: "02500/constant\\metadata.tsv"
  tensor_path: "02500/constant\\tensors.tsv"
}
embeddings {
  tensor_name: "month:02500"
  metadata_path: "02500/month\\metadata.tsv"
  tensor_path: "02500/month\\tensors.tsv"
}
embeddings {
  tensor_name: "summary:02500"
  metadata_path: "02500/summary\\metadata.tsv"
  tensor_path: "02500/summary\\tensors.tsv"
}
embeddings {
  tensor_name: "precip_type:02500"
  metadata_path: "02500/precip_type\\metadata.tsv"
  tensor_path: "02500/precip_type\\tensors.tsv"
}
