embeddings {
  tensor_name: "constant:01900"
  metadata_path: "01900/constant\\metadata.tsv"
  tensor_path: "01900/constant\\tensors.tsv"
}
embeddings {
  tensor_name: "month:01900"
  metadata_path: "01900/month\\metadata.tsv"
  tensor_path: "01900/month\\tensors.tsv"
}
embeddings {
  tensor_name: "summary:01900"
  metadata_path: "01900/summary\\metadata.tsv"
  tensor_path: "01900/summary\\tensors.tsv"
}
embeddings {
  tensor_name: "precip_type:01900"
  metadata_path: "01900/precip_type\\metadata.tsv"
  tensor_path: "01900/precip_type\\tensors.tsv"
}
